package club.maxstats.hyko

import kotlinx.serialization.*
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.json.*

@OptIn(ExperimentalSerializationApi::class)
@Serializer(forClass = Bedwars::class)
object BedwarsSerializer : KSerializer<Bedwars> {
    override fun deserialize(decoder: Decoder): Bedwars {
        val decoder = decoder as? JsonDecoder
            ?: throw SerializationException("Expected JsonDecoder for ${decoder::class}")

        val bedwars = decoder.decodeJsonElement() as JsonObject
        return Bedwars(
            decode(bedwars),
            decode(bedwars.getAllWithPrefix("four_four")),
            decode(bedwars.getAllWithPrefix("four_three")),
            decode(bedwars.getAllWithPrefix("eight_two")),
            decode(bedwars.getAllWithPrefix("eight_one")),
            decode(bedwars.getAllWithPrefix("two_four")),
            decode(bedwars.getAllWithPrefix("castle"))
        )
    }
}

@Serializable(with = BedwarsSerializer::class)
data class Bedwars(
    val overall: OverallBedwars = OverallBedwars(),
    val fourFour: FourFourBedwars = FourFourBedwars(),
    val fourThree: FourThreeBedwars = FourThreeBedwars(),
    val eightTwo: EightTwoBedwars = EightTwoBedwars(),
    val eightOne: EightOneBedwars = EightOneBedwars(),
    val twoFour: TwoFourBedwars = TwoFourBedwars(),
    val castle: CastleBedwars = CastleBedwars()
)

@Serializable
data class OverallBedwars(
    @SerialName("Experience_new") val experienceNew : Int = 0,
    @SerialName("first_join_7") val firstJoin7 : Boolean = true,
    @SerialName("Experience") val experience : Int = 0,
    @SerialName("games_played_bedwars_1") val gamesPlayed1 : Int = 0,
    @SerialName("winstreak") val winstreak : Int = 0,
    @SerialName("void_kills_bedwars") val voidKills : Int = 0,
    @SerialName("coins") val coins : Int = 0,
    @SerialName("games_played_bedwars") val gamesPlayed : Int = 0,
    @SerialName("entity_attack_final_kills_bedwars") val entityAttackFinalKills : Int = 0,
    @SerialName("kills_bedwars") val kills : Int = 0,
    @SerialName("entity_attack_kills_bedwars") val entityAttackKills : Int = 0,
    @SerialName("wins_bedwars") val wins : Int = 0,
    @SerialName("final_kills_bedwars") val finalKills : Int = 0,
    @SerialName("void_final_kills_bedwars") val voidFinalKills : Int = 0,
    @SerialName("beds_broken_bedwars") val bedsBroken : Int = 0,
    @SerialName("final_deaths_bedwars") val finalDeaths : Int = 0,
    @SerialName("void_deaths_bedwars") val voidDeaths : Int = 0,
    @SerialName("deaths_bedwars") val deaths : Int = 0,
    @SerialName("beds_lost_bedwars") val bedsLost : Int = 0,
    @SerialName("void_final_deaths_bedwars") val voidFinalDeaths : Int = 0,
    @SerialName("entity_attack_deaths_bedwars") val entityAttackDeaths : Int = 0,
    @SerialName("losses_bedwars") val losses : Int = 0,
    @SerialName("projectile_kills_bedwars") val projectileKills : Int = 0,
    @SerialName("fall_kills_bedwars") val fallKills : Int = 0,
    @SerialName("entity_attack_final_deaths_bedwars") val entityAttackFinalDeaths : Int = 0,
    @SerialName("chest_history") val chestHistory : String = "",
    @SerialName("fall_deaths_bedwars") val fallDeaths : Int = 0,
    @SerialName("activeNPCSkin") val activenpcskin : String = "",
    @SerialName("fall_final_kills_bedwars") val fallFinalKills : Int = 0,
    @SerialName("fall_final_deaths_bedwars") val fallFinalDeaths : Int = 0,
    @SerialName("fire_tick_deaths_bedwars") val fireTickDeaths : Int = 0,
    @SerialName("custom_final_kills_bedwars") val customFinalKills : Int = 0,
    @SerialName("entity_explosion_kills_bedwars") val entityExplosionKills : Int = 0,
    @SerialName("custom_deaths_bedwars") val customDeaths : Int = 0,
    @SerialName("entity_explosion_deaths_bedwars") val entityExplosionDeaths : Int = 0,
    @SerialName("activeKillEffect") val activekilleffect : String = "",
    @SerialName("activeVictoryDance") val activevictorydance : String = "",
    @SerialName("projectile_final_kills_bedwars") val projectileFinalKills : Int = 0,
    @SerialName("activeIslandTopper") val activeislandtopper : String = "",
    @SerialName("spray_glyph_field") val sprayGlyphField : String = "",
    @SerialName("activeKillMessages") val activekillmessages : String = "",
    @SerialName("activeDeathCry") val activedeathcry : String = "",
    @SerialName("spooky_open_ach") val spookyOpenAch : Int = 0,
    @SerialName("entity_explosion_final_deaths_bedwars") val entityExplosionFinalDeaths : Int = 0,
    @SerialName("entity_explosion_final_kills_bedwars") val entityExplosionFinalKills : Int = 0,
    @SerialName("activeProjectileTrail") val activeprojectiletrail : String = "",
    @SerialName("fire_deaths_bedwars") val fireDeaths : Int = 0,
    @SerialName("activeGlyph") val activeglyph : String = "",
    @SerialName("projectile_deaths_bedwars") val projectileDeaths : Int = 0,
    @SerialName("seen_beta_menu") val seenBetaMenu : Int = 0,
    @SerialName("favorite_slots") val favoriteSlots : String = "",
    @SerialName("activeBedDestroy") val activebeddestroy : String = "",
    @SerialName("favourites_2") val favourites2 : String = "",
    @SerialName("activeSprays") val activesprays : String = "",
    @SerialName("fire_tick_final_deaths_bedwars") val fireTickFinalDeaths : Int = 0,
    @SerialName("magic_final_kills_bedwars") val magicFinalKills : Int = 0,
    @SerialName("glyph_storage_new") val glyphStorageNew : String = "",
    @SerialName("spray_storage_new") val sprayStorageNew : String = "",
    @SerialName("projectile_final_deaths_bedwars") val projectileFinalDeaths : Int = 0,
    @SerialName("favourites_1") val favourites1 : String = "",
    @SerialName("fire_tick_final_kills_bedwars") val fireTickFinalKills : Int = 0,
    @SerialName("magic_deaths_bedwars") val magicDeaths : Int = 0,
    @SerialName("drowning_deaths_bedwars") val drowningDeaths : Int = 0,
    @SerialName("magic_kills_bedwars") val magicKills : Int = 0,
    @SerialName("magic_final_deaths_bedwars") val magicFinalDeaths : Int = 0,
    @SerialName("fire_tick_kills_bedwars") val fireTickKills : Int = 0,
    @SerialName("fire_kills_bedwars") val fireKills : Int = 0,
    @SerialName("shop_sort") val shopSort : String = "",
    @SerialName("suffocation_final_deaths_bedwars") val suffocationFinalDeaths : Int = 0,
    @SerialName("shop_sort_enable_owned_first") val shopSortEnableOwnedFirst : Boolean = true,
)

@Serializable
data class FourFourBedwars(
    @SerialName("four_four_beds_broken_bedwars") val bedsBroken : Int = 0,
    @SerialName("four_four_games_played_bedwars") val gamesPlayed : Int = 0,
    @SerialName("four_four_wins_bedwars") val wins : Int = 0,
    @SerialName("four_four_entity_attack_final_kills_bedwars") val entityAttackFinalKills : Int = 0,
    @SerialName("four_four_final_kills_bedwars") val finalKills : Int = 0,
    @SerialName("four_four_void_kills_bedwars") val voidKills : Int = 0,
    @SerialName("four_four_kills_bedwars") val kills : Int = 0,
    @SerialName("four_four_deaths_bedwars") val deaths : Int = 0,
    @SerialName("four_four_entity_attack_deaths_bedwars") val entityAttackDeaths : Int = 0,
    @SerialName("four_four_entity_attack_kills_bedwars") val entityAttackKills : Int = 0,
    @SerialName("four_four_void_final_kills_bedwars") val voidFinalKills : Int = 0,
    @SerialName("four_four_void_deaths_bedwars") val voidDeaths : Int = 0,
    @SerialName("four_four_beds_lost_bedwars") val bedsLost : Int = 0,
    @SerialName("four_four_fall_deaths_bedwars") val fallDeaths : Int = 0,
    @SerialName("four_four_final_deaths_bedwars") val finalDeaths : Int = 0,
    @SerialName("four_four_entity_attack_final_deaths_bedwars") val entityAttackFinalDeaths : Int = 0,
    @SerialName("four_four_fall_final_kills_bedwars") val fallFinalKills : Int = 0,
    @SerialName("four_four_fall_kills_bedwars") val fallKills : Int = 0,
    @SerialName("four_four_void_final_deaths_bedwars") val voidFinalDeaths : Int = 0,
    @SerialName("four_four_losses_bedwars") val losses : Int = 0,
    @SerialName("four_four_fall_final_deaths_bedwars") val fallFinalDeaths : Int = 0,
    @SerialName("four_four_fire_tick_deaths_bedwars") val fireTickDeaths : Int = 0,
    @SerialName("four_four_custom_final_kills_bedwars") val customFinalKills : Int = 0,
    @SerialName("four_four_entity_explosion_kills_bedwars") val entityExplosionKills : Int = 0,
    @SerialName("four_four_custom_deaths_bedwars") val customDeaths : Int = 0,
    @SerialName("four_four_entity_explosion_deaths_bedwars") val entityExplosionDeaths : Int = 0,
    @SerialName("four_four_projectile_final_kills_bedwars") val projectileFinalKills : Int = 0,
    @SerialName("four_four_entity_explosion_final_kills_bedwars") val entityExplosionFinalKills : Int = 0,
    @SerialName("four_four_winstreak") val winstreak : Int = 0,
    @SerialName("four_four_projectile_deaths_bedwars") val projectileDeaths : Int = 0,
    @SerialName("four_four_entity_explosion_final_deaths_bedwars") val entityExplosionFinalDeaths : Int = 0,
    @SerialName("four_four_fire_deaths_bedwars") val fireDeaths : Int = 0,
    @SerialName("four_four_fire_tick_final_kills_bedwars") val fireTickFinalKills : Int = 0,
    @SerialName("four_four_projectile_final_deaths_bedwars") val projectileFinalDeaths : Int = 0,
    @SerialName("four_four_projectile_kills_bedwars") val projectileKills : Int = 0,
    @SerialName("four_four_fire_tick_kills_bedwars") val fireTickKills : Int = 0,
    @SerialName("four_four_fire_tick_final_deaths_bedwars") val fireTickFinalDeaths : Int = 0,
    @SerialName("four_four_magic_kills_bedwars") val magicKills : Int = 0,
    @SerialName("four_four_magic_deaths_bedwars") val magicDeaths : Int = 0,
    @SerialName("four_four_magic_final_kills_bedwars") val magicFinalKills : Int = 0,
    @SerialName("four_four_fire_kills_bedwars") val fireKills : Int = 0,
)

@Serializable
data class FourThreeBedwars(
    @SerialName("four_three_void_final_kills_bedwars") val voidFinalKills : Int = 0,
    @SerialName("four_three_wins_bedwars") val wins : Int = 0,
    @SerialName("four_three_games_played_bedwars") val gamesPlayed : Int = 0,
    @SerialName("four_three_custom_final_kills_bedwars") val customFinalKills : Int = 0,
    @SerialName("four_three_fall_deaths_bedwars") val fallDeaths : Int = 0,
    @SerialName("four_three_beds_lost_bedwars") val bedsLost : Int = 0,
    @SerialName("four_three_deaths_bedwars") val deaths : Int = 0,
    @SerialName("four_three_beds_broken_bedwars") val bedsBroken : Int = 0,
    @SerialName("four_three_entity_attack_final_kills_bedwars") val entityAttackFinalKills : Int = 0,
    @SerialName("four_three_void_final_deaths_bedwars") val voidFinalDeaths : Int = 0,
    @SerialName("four_three_final_kills_bedwars") val finalKills : Int = 0,
    @SerialName("four_three_final_deaths_bedwars") val finalDeaths : Int = 0,
    @SerialName("four_three_entity_attack_deaths_bedwars") val entityAttackDeaths : Int = 0,
    @SerialName("four_three_void_deaths_bedwars") val voidDeaths : Int = 0,
    @SerialName("four_three_entity_attack_kills_bedwars") val entityAttackKills : Int = 0,
    @SerialName("four_three_kills_bedwars") val kills : Int = 0,
    @SerialName("four_three_void_kills_bedwars") val voidKills : Int = 0,
    @SerialName("four_three_entity_attack_final_deaths_bedwars") val entityAttackFinalDeaths : Int = 0,
    @SerialName("four_three_losses_bedwars") val losses : Int = 0,
    @SerialName("four_three_fall_final_kills_bedwars") val fallFinalKills : Int = 0,
    @SerialName("four_three_entity_explosion_kills_bedwars") val entityExplosionKills : Int = 0,
    @SerialName("four_three_entity_explosion_deaths_bedwars") val entityExplosionDeaths : Int = 0,
    @SerialName("four_three_fall_kills_bedwars") val fallKills : Int = 0,
    @SerialName("four_three_fall_final_deaths_bedwars") val fallFinalDeaths : Int = 0,
    @SerialName("four_three_fire_tick_deaths_bedwars") val fireTickDeaths : Int = 0,
    @SerialName("four_three_projectile_final_kills_bedwars") val projectileFinalKills : Int = 0,
    @SerialName("four_three_fire_deaths_bedwars") val fireDeaths : Int = 0,
    @SerialName("four_three_projectile_deaths_bedwars") val projectileDeaths : Int = 0,
    @SerialName("four_three_winstreak") val winstreak : Int = 0,
    @SerialName("four_three_entity_explosion_final_kills_bedwars") val entityExplosionFinalKills : Int = 0,
    @SerialName("four_three_fire_tick_final_deaths_bedwars") val fireTickFinalDeaths : Int = 0,
    @SerialName("four_three_projectile_final_deaths_bedwars") val projectileFinalDeaths : Int = 0,
    @SerialName("four_three_entity_explosion_final_deaths_bedwars") val entityExplosionFinalDeaths : Int = 0,
    @SerialName("four_three_fire_kills_bedwars") val fireKills : Int = 0,
    @SerialName("four_three_fire_tick_kills_bedwars") val fireTickKills : Int = 0,
    @SerialName("four_three_fire_tick_final_kills_bedwars") val fireTickFinalKills : Int = 0,
    @SerialName("four_three_magic_final_deaths_bedwars") val magicFinalDeaths : Int = 0,
    @SerialName("four_three_magic_deaths_bedwars") val magicDeaths : Int = 0,
    @SerialName("four_three_magic_final_kills_bedwars") val magicFinalKills : Int = 0,
    @SerialName("four_three_projectile_kills_bedwars") val projectileKills : Int = 0,
)

@Serializable
data class EightTwoBedwars(
    @SerialName("eight_two_beds_broken_bedwars") val bedsBroken : Int = 0,
    @SerialName("eight_two_wins_bedwars") val wins : Int = 0,
    @SerialName("eight_two_kills_bedwars") val kills : Int = 0,
    @SerialName("eight_two_entity_attack_final_kills_bedwars") val entityAttackFinalKills : Int = 0,
    @SerialName("eight_two_entity_attack_kills_bedwars") val entityAttackKills : Int = 0,
    @SerialName("eight_two_void_kills_bedwars") val voidKills : Int = 0,
    @SerialName("eight_two_games_played_bedwars") val gamesPlayed : Int = 0,
    @SerialName("eight_two_void_final_kills_bedwars") val voidFinalKills : Int = 0,
    @SerialName("eight_two_final_kills_bedwars") val finalKills : Int = 0,
    @SerialName("eight_two_void_deaths_bedwars") val voidDeaths : Int = 0,
    @SerialName("eight_two_final_deaths_bedwars") val finalDeaths : Int = 0,
    @SerialName("eight_two_void_final_deaths_bedwars") val voidFinalDeaths : Int = 0,
    @SerialName("eight_two_deaths_bedwars") val deaths : Int = 0,
    @SerialName("eight_two_beds_lost_bedwars") val bedsLost : Int = 0,
    @SerialName("eight_two_entity_attack_deaths_bedwars") val entityAttackDeaths : Int = 0,
    @SerialName("eight_two_losses_bedwars") val losses : Int = 0,
    @SerialName("eight_two_projectile_kills_bedwars") val projectileKills : Int = 0,
    @SerialName("eight_two_fall_kills_bedwars") val fallKills : Int = 0,
    @SerialName("eight_two_entity_attack_final_deaths_bedwars") val entityAttackFinalDeaths : Int = 0,
    @SerialName("eight_two_fall_deaths_bedwars") val fallDeaths : Int = 0,
    @SerialName("eight_two_entity_explosion_deaths_bedwars") val entityExplosionDeaths : Int = 0,
    @SerialName("eight_two_fall_final_kills_bedwars") val fallFinalKills : Int = 0,
    @SerialName("eight_two_projectile_final_kills_bedwars") val projectileFinalKills : Int = 0,
    @SerialName("eight_two_entity_explosion_kills_bedwars") val entityExplosionKills : Int = 0,
    @SerialName("eight_two_fall_final_deaths_bedwars") val fallFinalDeaths : Int = 0,
    @SerialName("eight_two_fire_tick_deaths_bedwars") val fireTickDeaths : Int = 0,
    @SerialName("eight_two_entity_explosion_final_deaths_bedwars") val entityExplosionFinalDeaths : Int = 0,
    @SerialName("eight_two_entity_explosion_final_kills_bedwars") val entityExplosionFinalKills : Int = 0,
    @SerialName("eight_two_winstreak") val winstreak : Int = 0,
    @SerialName("eight_two_projectile_deaths_bedwars") val projectileDeaths : Int = 0,
    @SerialName("eight_two_magic_deaths_bedwars") val magicDeaths : Int = 0,
    @SerialName("eight_two_projectile_final_deaths_bedwars") val projectileFinalDeaths : Int = 0,
    @SerialName("eight_two_magic_kills_bedwars") val magicKills : Int = 0,
    @SerialName("eight_two_magic_final_deaths_bedwars") val magicFinalDeaths : Int = 0,
    @SerialName("eight_two_fire_tick_kills_bedwars") val fireTickKills : Int = 0,
    @SerialName("eight_two_magic_final_kills_bedwars") val magicFinalKills : Int = 0,
    @SerialName("eight_two_fire_tick_final_kills_bedwars") val fireTickFinalKills : Int = 0,
    @SerialName("eight_two_suffocation_final_deaths_bedwars") val suffocationFinalDeaths : Int = 0,
    @SerialName("eight_two_fire_tick_final_deaths_bedwars") val fireTickFinalDeaths : Int = 0,
)

@Serializable
data class EightOneBedwars(
    @SerialName("eight_one_beds_lost_bedwars") val bedsLost : Int = 0,
    @SerialName("eight_one_entity_attack_final_kills_bedwars") val entityAttackFinalKills : Int = 0,
    @SerialName("eight_one_final_deaths_bedwars") val finalDeaths : Int = 0,
    @SerialName("eight_one_games_played_bedwars") val gamesPlayed : Int = 0,
    @SerialName("eight_one_final_kills_bedwars") val finalKills : Int = 0,
    @SerialName("eight_one_beds_broken_bedwars") val bedsBroken : Int = 0,
    @SerialName("eight_one_entity_attack_final_deaths_bedwars") val entityAttackFinalDeaths : Int = 0,
    @SerialName("eight_one_losses_bedwars") val losses : Int = 0,
    @SerialName("eight_one_entity_attack_kills_bedwars") val entityAttackKills : Int = 0,
    @SerialName("eight_one_void_kills_bedwars") val voidKills : Int = 0,
    @SerialName("eight_one_void_final_kills_bedwars") val voidFinalKills : Int = 0,
    @SerialName("eight_one_kills_bedwars") val kills : Int = 0,
    @SerialName("eight_one_deaths_bedwars") val deaths : Int = 0,
    @SerialName("eight_one_entity_attack_deaths_bedwars") val entityAttackDeaths : Int = 0,
    @SerialName("eight_one_wins_bedwars") val wins : Int = 0,
    @SerialName("eight_one_void_deaths_bedwars") val voidDeaths : Int = 0,
    @SerialName("eight_one_projectile_final_kills_bedwars") val projectileFinalKills : Int = 0,
    @SerialName("eight_one_fall_final_kills_bedwars") val fallFinalKills : Int = 0,
    @SerialName("eight_one_projectile_kills_bedwars") val projectileKills : Int = 0,
    @SerialName("eight_one_void_final_deaths_bedwars") val voidFinalDeaths : Int = 0,
    @SerialName("eight_one_fall_kills_bedwars") val fallKills : Int = 0,
    @SerialName("eight_one_entity_explosion_kills_bedwars") val entityExplosionKills : Int = 0,
    @SerialName("eight_one_entity_explosion_deaths_bedwars") val entityExplosionDeaths : Int = 0,
    @SerialName("eight_one_fall_deaths_bedwars") val fallDeaths : Int = 0,
    @SerialName("eight_one_winstreak") val winstreak : Int = 0,
    @SerialName("eight_one_entity_explosion_final_kills_bedwars") val entityExplosionFinalKills : Int = 0,
    @SerialName("eight_one_magic_final_kills_bedwars") val magicFinalKills : Int = 0,
    @SerialName("eight_one_projectile_deaths_bedwars") val projectileDeaths : Int = 0,
    @SerialName("eight_one_projectile_final_deaths_bedwars") val projectileFinalDeaths : Int = 0,
    @SerialName("eight_one_fall_final_deaths_bedwars") val fallFinalDeaths : Int = 0,
    @SerialName("eight_one_entity_explosion_final_deaths_bedwars") val entityExplosionFinalDeaths : Int = 0,
    @SerialName("eight_one_drowning_deaths_bedwars") val drowningDeaths : Int = 0,
    @SerialName("eight_one_fire_tick_deaths_bedwars") val fireTickDeaths : Int = 0,
    @SerialName("eight_one_magic_kills_bedwars") val magicKills : Int = 0,
    @SerialName("eight_one_fire_tick_kills_bedwars") val fireTickKills : Int = 0,
    @SerialName("eight_one_magic_deaths_bedwars") val magicDeaths : Int = 0,
    @SerialName("eight_one_magic_final_deaths_bedwars") val magicFinalDeaths : Int = 0,
)

@Serializable
data class TwoFourBedwars(
    @SerialName("two_four_winstreak") val winstreak : Int = 0,
    @SerialName("two_four_games_played_bedwars") val gamesPlayed : Int = 0,
    @SerialName("two_four_wins_bedwars") val wins : Int = 0,
    @SerialName("two_four_beds_broken_bedwars") val bedsBroken : Int = 0,
    @SerialName("two_four_deaths_bedwars") val deaths : Int = 0,
    @SerialName("two_four_entity_attack_deaths_bedwars") val entityAttackDeaths : Int = 0,
    @SerialName("two_four_fall_kills_bedwars") val fallKills : Int = 0,
    @SerialName("two_four_kills_bedwars") val kills : Int = 0,
    @SerialName("two_four_void_deaths_bedwars") val voidDeaths : Int = 0,
    @SerialName("two_four_entity_attack_final_kills_bedwars") val entityAttackFinalKills : Int = 0,
    @SerialName("two_four_entity_attack_kills_bedwars") val entityAttackKills : Int = 0,
    @SerialName("two_four_final_kills_bedwars") val finalKills : Int = 0,
    @SerialName("two_four_void_final_kills_bedwars") val voidFinalKills : Int = 0,
    @SerialName("two_four_void_kills_bedwars") val voidKills : Int = 0,
    @SerialName("two_four_fall_final_kills_bedwars") val fallFinalKills : Int = 0,
    @SerialName("two_four_fall_deaths_bedwars") val fallDeaths : Int = 0,
    @SerialName("two_four_fire_tick_kills_bedwars") val fireTickKills : Int = 0,
    @SerialName("two_four_beds_lost_bedwars") val bedsLost : Int = 0,
    @SerialName("two_four_entity_attack_final_deaths_bedwars") val entityAttackFinalDeaths : Int = 0,
    @SerialName("two_four_final_deaths_bedwars") val finalDeaths : Int = 0,
    @SerialName("two_four_losses_bedwars") val losses : Int = 0,
    @SerialName("two_four_magic_final_kills_bedwars") val magicFinalKills : Int = 0,
    @SerialName("two_four_magic_kills_bedwars") val magicKills : Int = 0,
    @SerialName("two_four_void_final_deaths_bedwars") val voidFinalDeaths : Int = 0,
    @SerialName("two_four_magic_deaths_bedwars") val magicDeaths : Int = 0,
    @SerialName("two_four_magic_final_deaths_bedwars") val magicFinalDeaths : Int = 0,
    @SerialName("two_four_fall_final_deaths_bedwars") val fallFinalDeaths : Int = 0,
    @SerialName("two_four_entity_explosion_kills_bedwars") val entityExplosionKills : Int = 0,
    @SerialName("two_four_projectile_deaths_bedwars") val projectileDeaths : Int = 0,
)

@Serializable
data class CastleBedwars(
    @SerialName("castle_winstreak") val winstreak : Int = 0,
    @SerialName("castle_deaths_bedwars") val deaths : Int = 0,
    @SerialName("castle_games_played_bedwars") val gamesPlayed : Int = 0,
    @SerialName("castle_wins_bedwars") val wins : Int = 0,
    @SerialName("castle_void_deaths_bedwars") val voidDeaths : Int = 0,
    @SerialName("castle_beds_lost_bedwars") val bedsLost : Int = 0,
    @SerialName("castle_beds_broken_bedwars") val bedsBroken : Int = 0,
    @SerialName("castle_fall_kills_bedwars") val fallKills : Int = 0,
    @SerialName("castle_entity_attack_kills_bedwars") val entityAttackKills : Int = 0,
    @SerialName("castle_entity_attack_deaths_bedwars") val entityAttackDeaths : Int = 0,
    @SerialName("castle_fall_deaths_bedwars") val fallDeaths : Int = 0,
    @SerialName("castle_void_kills_bedwars") val voidKills : Int = 0,
    @SerialName("castle_kills_bedwars") val kills : Int = 0,
    @SerialName("castle_final_deaths_bedwars") val finalDeaths : Int = 0,
    @SerialName("castle_fall_final_deaths_bedwars") val fallFinalDeaths : Int = 0,
    @SerialName("castle_losses_bedwars") val losses : Int = 0,
    @SerialName("castle_void_final_deaths_bedwars") val voidFinalDeaths : Int = 0,
    @SerialName("castle_entity_attack_final_kills_bedwars") val entityAttackFinalKills : Int = 0,
    @SerialName("castle_final_kills_bedwars") val finalKills : Int = 0,
    @SerialName("castle_entity_attack_final_deaths_bedwars") val entityAttackFinalDeaths : Int = 0,
    @SerialName("castle_void_final_kills_bedwars") val voidFinalKills : Int = 0,
    @SerialName("castle_drowning_deaths_bedwars") val drowningDeaths : Int = 0,
    @SerialName("castle_magic_deaths_bedwars") val magicDeaths : Int = 0,
    @SerialName("castle_projectile_deaths_bedwars") val projectileDeaths : Int = 0,
    @SerialName("castle_fire_tick_kills_bedwars") val fireTickKills : Int = 0,
    @SerialName("castle_entity_explosion_final_deaths_bedwars") val entityExplosionFinalDeaths : Int = 0,
    @SerialName("castle_fall_final_kills_bedwars") val fallFinalKills : Int = 0,
    @SerialName("castle_entity_explosion_deaths_bedwars") val entityExplosionDeaths : Int = 0,
    @SerialName("castle_entity_explosion_kills_bedwars") val entityExplosionKills : Int = 0,
    @SerialName("castle_entity_explosion_final_kills_bedwars") val entityExplosionFinalKills : Int = 0,
    @SerialName("castle_suffocation_kills_bedwars") val suffocationKills : Int = 0,
    @SerialName("castle_projectile_final_deaths_bedwars") val projectileFinalDeaths : Int = 0,
)