package club.maxstats.hyko

import kotlinx.serialization.*
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.json.JsonDecoder
import kotlinx.serialization.json.JsonObject

@OptIn(ExperimentalSerializationApi::class)
@Serializer(forClass = Duels::class)
object DuelsSerializer : KSerializer<Duels> {
    override fun deserialize(decoder: Decoder): Duels {
        val decoder = decoder as? JsonDecoder
            ?: throw SerializationException("Expected JsonDecoder for ${decoder::class}")

        val duels = decoder.decodeJsonElement() as? JsonObject
            ?: throw SerializationException("Expected object for DuelsSerializer")

        return Duels(
            decode(duels),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_DUEL_ARENA.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_BLITZ_DUEL.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_BOW_DUEL.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_BOWSPLEEF_DUEL.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_BOXING_DUEL.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_BRIDGE_DUEL.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_BRIDGE_DOUBLES.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_BRIDGE_THREES.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_BRIDGE_FOUR.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_BRIDGE_2V2V2V2.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_BRIDGE_3V3V3V3.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_CAPTURE_THREES.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_BRIDGE_TOURNAMENT.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_CLASSIC_DUEL.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_COMBO_DUEL.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_MW_DUEL.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_MW_DOUBLES.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_MW_FOUR.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_POTION_DUEL.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_OP_DUEL.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_OP_DOUBLES.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_PARKOUR_EIGHT.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_SW_DUEL.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_SW_DOUBLES.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_SW_FOUR.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_SW_TOURNAMENT.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_SUMO_DUEL.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_SUMO_TOURNAMENT.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_UHC_DUEL.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_UHC_DOUBLES.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_UHC_FOUR.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_UHC_MEETUP.getAPIName())),
            decode(duels.getAllWithPrefix(DuelsNames.DUELS_UHC_TOURNAMENT.getAPIName()))
        )
    }
}

enum class DuelsNames(val formattedName: String) {
    DUELS_DUEL_ARENA("ArenaDuels"),
    DUELS_BLITZ_DUEL("BlitzDuels"),
    DUELS_BOW_DUEL("BowDuels"),
    DUELS_BOWSPLEEF_DUEL("BowSpleefDuels"),
    DUELS_BOXING_DUEL("BoxingDuels"),
    DUELS_BRIDGE_THREES("Bridge3v3Duels"),
    DUELS_CAPTURE_THREES("BridgeCTF3v3Duels"),
    DUELS_BRIDGE_DOUBLES("BridgeDoublesDuels"),
    DUELS_BRIDGE_DUEL("BridgeDuels"),
    DUELS_BRIDGE_3V3V3V3("BridgeFourThreeDuels"),
    DUELS_BRIDGE_2V2V2V2("BridgeFourTwoDuels"),
    DUELS_BRIDGE_FOUR("BridgeTeamsDuels"),
    DUELS_BRIDGE_TOURNAMENT("BridgeTournamentDuels"),
    DUELS_CLASSIC_DUEL("ClassicDuels"),
    DUELS_COMBO_DUEL("ComboDuels"),
    DUELS_MW_DOUBLES("MegaWallsDoublesDuels"),
    DUELS_MW_DUEL("MegaWallsDuels"),
    DUELS_MW_FOUR("MegaWallsTeamsDuels"),
    DUELS_POTION_DUEL("NoDebuffDuels"),
    DUELS_OP_DOUBLES("OPDoublesDuels"),
    DUELS_OP_DUEL("OPDuels"),
    DUELS_PARKOUR_EIGHT("ParkourDuels"),
    DUELS_SW_DOUBLES("SkywarsDoublesDuels"),
    DUELS_SW_DUEL("SkywarsDuels"),
    DUELS_SW_FOUR("SkywarsTeamsDuels"),
    DUELS_SW_TOURNAMENT("SkywarsTournamentDuels"),
    DUELS_SUMO_DUEL("SumoDuels"),
    DUELS_SUMO_TOURNAMENT("SumoTournamentDuels"),
    DUELS_UHC_MEETUP("UHCDeathmatchDuels"),
    DUELS_UHC_DOUBLES("UHCDoublesDuels"),
    DUELS_UHC_DUEL("UHCDuels"),
    DUELS_UHC_FOUR("UHCTeamsDuels"),
    DUELS_UHC_TOURNAMENT("UHCTournamentDuels");

    override fun toString(): String {
        return formattedName
    }

    fun getAPIName(): String = this.name.replace("DUELS_", "").lowercase()
}

@Serializable(with = DuelsSerializer::class)
data class Duels(
    val overall: OverallDuels = OverallDuels(),
    val arena: ArenaDuels = ArenaDuels(),
    val blitz: BlitzDuels = BlitzDuels(),
    val bow: BowDuels = BowDuels(),
    val bowSpleef: BowSpleefDuels = BowSpleefDuels(),
    val boxing: BoxingDuels = BoxingDuels(),
    val bridge: BridgeDuels = BridgeDuels(),
    val bridgeDoubles: BridgeDoublesDuels = BridgeDoublesDuels(),
    val bridge3v3: Bridge3v3Duels = Bridge3v3Duels(),
    val bridge4v4: Bridge4v4Duels = Bridge4v4Duels(),
    val bridge2v2v2v2: BridgeFourTwoDuels = BridgeFourTwoDuels(),
    val bridge3v3v3v3: BridgeFourThreeDuels = BridgeFourThreeDuels(),
    val bridgeCTF: BridgeCTF3v3Duels = BridgeCTF3v3Duels(),
    val bridgeTournament: BridgeTournamentDuels = BridgeTournamentDuels(),
    val classic: ClassicDuels = ClassicDuels(),
    val combo: ComboDuels = ComboDuels(),
    val megawalls: MegaWallsDuels = MegaWallsDuels(),
    val megawallsDoubles: MegaWallsDoublesDuels = MegaWallsDoublesDuels(),
    val megawallsTeams: MegaWallsTeamsDuels = MegaWallsTeamsDuels(),
    val noDebuff: NoDebuffDuels = NoDebuffDuels(),
    val op: OPDuels = OPDuels(),
    val opDoubles: OPDoublesDuels = OPDoublesDuels(),
    val parkour: ParkourDuels = ParkourDuels(),
    val skywars: SkywarsDuels = SkywarsDuels(),
    val skywarsDoubles: SkywarsDoublesDuels = SkywarsDoublesDuels(),
    val skywarsTeamsDuels: SkywarsTeamsDuels = SkywarsTeamsDuels(),
    val skywarsTournament: SkywarsTournamentDuels = SkywarsTournamentDuels(),
    val sumo: SumoDuels = SumoDuels(),
    val sumoTournament: SumoTournamentDuels = SumoTournamentDuels(),
    val uhc: UHCDuels = UHCDuels(),
    val uhcDoubles: UHCDoublesDuels = UHCDoublesDuels(),
    val uhcTeams: UHCTeamsDuels = UHCTeamsDuels(),
    val uhcDeathmatch: UHCDeathmatchDuels = UHCDeathmatchDuels(),
    val uhcTournament: UHCTournamentDuels = UHCTournamentDuels()
)

@Serializable
data class ArenaDuels(
    @SerialName("duel_arena_damage_dealt") val damageDealt: Int = 0,
    @SerialName("duel_arena_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("duel_arena_kills") val kills: Int = 0,
    @SerialName("duel_arena_melee_hits") val meleeHits: Int = 0,
    @SerialName("duel_arena_melee_swings") val meleeSwings: Int = 0,
    @SerialName("duel_arena_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("duel_arena_wins") val wins: Int = 0,
    @SerialName("duel_arena_bow_hits") val bowHits: Int = 0,
    @SerialName("duel_arena_bow_shots") val bowShots: Int = 0,
    @SerialName("duel_arena_blocks_placed") val blocksPlaced: Int = 0,
    @SerialName("duel_arena_deaths") val deaths: Int = 0,
    @SerialName("duel_arena_losses") val losses: Int = 0,
    @SerialName("best_winstreak_mode_duel_arena") val bestWinstreak: Int = 0,
    @SerialName("current_winstreak_mode_duel_arena") val currentWinstreak: Int = 0,
)

@Serializable
data class BlitzDuels(
    @SerialName("blitz_duels_kit") val sKit: String = "",
    @SerialName("duels_winstreak_best_blitz_duel") val duelsWinstreakBest: Int = 0,
    @SerialName("blitz_duel_melee_swings") val meleeSwings: Int = 0,
    @SerialName("blitz_duel_damage_dealt") val damageDealt: Int = 0,
    @SerialName("blitz_duel_melee_hits") val meleeHits: Int = 0,
    @SerialName("blitz_duel_bow_shots") val bowShots: Int = 0,
    @SerialName("blitz_duel_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("blitz_duel_wins") val wins: Int = 0,
    @SerialName("blitz_duel_bow_hits") val bowHits: Int = 0,
    @SerialName("blitz_duel_kills") val kills: Int = 0,
    @SerialName("blitz_duel_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("blitz_duel_losses") val losses: Int = 0,
    @SerialName("blitz_duel_deaths") val deaths: Int = 0,
    @SerialName("blitz_duel_kit_wins") val kitWins: Int = 0,
    @SerialName("blitz_duel_pigman_kit_wins") val pigmanKitWins: Int = 0,
    @SerialName("blitz_duel_archer_kit_wins") val archerKitWins: Int = 0,
    @SerialName("blitz_duel_baker_kit_wins") val bakerKitWins: Int = 0,
    @SerialName("blitz_duel_armorer_kit_wins") val armorerKitWins: Int = 0,
    @SerialName("blitz_duel_farmer_kit_wins") val farmerKitWins: Int = 0,
    @SerialName("blitz_duel_blocks_placed") val blocksPlaced: Int = 0,
    @SerialName("blitz_duel_fisherman_kit_wins") val fishermanKitWins: Int = 0,
    @SerialName("current_winstreak_mode_blitz_duel") val currentWinstreak: Int = 0,
    @SerialName("best_winstreak_mode_blitz_duel") val bestWinstreak: Int = 0,
    @SerialName("blitz_duel_wolftamer_kit_wins") val wolftamerKitWins: Int = 0,
    @SerialName("blitz_duel_necromancer_kit_wins") val necromancerKitWins: Int = 0,
    @SerialName("blitz_duel_warrior_kit_wins") val warriorKitWins: Int = 0,
    @SerialName("blitz_duel_knight_kit_wins") val knightKitWins: Int = 0,
    @SerialName("blitz_duel_reddragon_kit_wins") val reddragonKitWins: Int = 0,
    @SerialName("blitz_duel_golem_kit_wins") val golemKitWins: Int = 0,
    @SerialName("blitz_duel_troll_kit_wins") val trollKitWins: Int = 0,
    @SerialName("blitz_duel_blaze_kit_wins") val blazeKitWins: Int = 0,
    @SerialName("blitz_duel_toxicologist_kit_wins") val toxicologistKitWins: Int = 0,
    @SerialName("blitz_duel_rambo_kit_wins") val ramboKitWins: Int = 0,
    @SerialName("blitz_duel_arachnologist_kit_wins") val arachnologistKitWins: Int = 0,
    @SerialName("blitz_duel_scout_kit_wins") val scoutKitWins: Int = 0,
    @SerialName("blitz_duel_jockey_kit_wins") val jockeyKitWins: Int = 0,
    @SerialName("blitz_duel_donkeytamer_kit_wins") val donkeytamerKitWins: Int = 0,
    @SerialName("blitz_duel_hunter_kit_wins") val hunterKitWins: Int = 0,
    @SerialName("blitz_duel_snowman_kit_wins") val snowmanKitWins: Int = 0,
    @SerialName("blitz_duel_tim_kit_wins") val timKitWins: Int = 0,
    @SerialName("blitz_duel_rogue_kit_wins") val rogueKitWins: Int = 0,
    @SerialName("blitz_duel_ranger_kit_wins") val rangerKitWins: Int = 0,
    @SerialName("blitz_duel_guardian_kit_wins") val guardianKitWins: Int = 0,
    @SerialName("blitz_duel_heal_pots_used") val healPotsUsed: Int = 0,
    @SerialName("blitz_duel_slimeyslime_kit_wins") val slimeyslimeKitWins: Int = 0,
    @SerialName("blitz_duel_florist_kit_wins") val floristKitWins: Int = 0,
    @SerialName("blitz_duel_reaper_kit_wins") val reaperKitWins: Int = 0,
    @SerialName("blitz_duel_astronaut_kit_wins") val astronautKitWins: Int = 0,
    @SerialName("blitz_duel_shark_kit_wins") val sharkKitWins: Int = 0,
)

@Serializable
data class BowDuels(
    @SerialName("bow_duel_bow_hits") val bowHits: Int = 0,
    @SerialName("bow_duel_deaths") val deaths: Int = 0,
    @SerialName("bow_duel_losses") val losses: Int = 0,
    @SerialName("bow_duel_bow_shots") val bowShots: Int = 0,
    @SerialName("bow_duel_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("bow_duel_damage_dealt") val damageDealt: Int = 0,
    @SerialName("bow_duel_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("bow_duel_wins") val wins: Int = 0,
    @SerialName("bow_duel_kills") val kills: Int = 0,
    @SerialName("duels_winstreak_best_bow_duel") val duelsWinstreakBest: Int = 0,
    @SerialName("current_winstreak_mode_bow_duel") val currentWinstreak: Int = 0,
    @SerialName("best_winstreak_mode_bow_duel") val bestWinstreak: Int = 0,
)

@Serializable
data class BowSpleefDuels(
    @SerialName("bowspleef_duel_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("bowspleef_duel_bow_shots") val bowShots: Int = 0,
    @SerialName("bowspleef_duel_wins") val wins: Int = 0,
    @SerialName("duels_winstreak_best_bowspleef_duel") val duelsWinstreakBest: Int = 0,
    @SerialName("bowspleef_duel_deaths") val deaths: Int = 0,
    @SerialName("bowspleef_duel_losses") val losses: Int = 0,
    @SerialName("best_winstreak_mode_bowspleef_duel") val bestWinstreak: Int = 0,
    @SerialName("current_winstreak_mode_bowspleef_duel") val currentWinstreak: Int = 0,
)

@Serializable
data class BoxingDuels(
    @SerialName("boxing_duel_kills") val kills: Int = 0,
    @SerialName("boxing_duel_melee_hits") val meleeHits: Int = 0,
    @SerialName("boxing_duel_melee_swings") val meleeSwings: Int = 0,
    @SerialName("boxing_duel_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("boxing_duel_wins") val wins: Int = 0,
    @SerialName("boxing_duel_losses") val losses: Int = 0,
    @SerialName("boxing_duel_deaths") val deaths: Int = 0,
    @SerialName("best_winstreak_mode_boxing_duel") val bestWinstreak: Int = 0,
)

@Serializable
data class Bridge3v3Duels(
    @SerialName("bridge_threes_blocks_placed") val blocksPlaced: Int = 0,
    @SerialName("bridge_threes_bow_hits") val bowHits: Int = 0,
    @SerialName("bridge_threes_bow_shots") val bowShots: Int = 0,
    @SerialName("bridge_threes_bridge_deaths") val bridgeDeaths: Int = 0,
    @SerialName("bridge_threes_bridge_kills") val bridgeKills: Int = 0,
    @SerialName("bridge_threes_damage_dealt") val damageDealt: Int = 0,
    @SerialName("bridge_threes_goals") val goals: Int = 0,
    @SerialName("bridge_threes_melee_hits") val meleeHits: Int = 0,
    @SerialName("bridge_threes_melee_swings") val meleeSwings: Int = 0,
    @SerialName("bridge_threes_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("bridge_threes_wins") val wins: Int = 0,
    @SerialName("bridge_threes_losses") val losses: Int = 0,
    @SerialName("bridge_threes_golden_apples_eaten") val goldenApplesEaten: Int = 0,
    @SerialName("best_winstreak_mode_bridge_threes") val bestWinstreak: Int = 0,
)

@Serializable
data class BridgeCTF3v3Duels(
    @SerialName("capture_threes_blocks_placed") val blocksPlaced: Int = 0,
    @SerialName("capture_threes_bow_hits") val bowHits: Int = 0,
    @SerialName("capture_threes_bow_shots") val bowShots: Int = 0,
    @SerialName("capture_threes_bridge_deaths") val bridgeDeaths: Int = 0,
    @SerialName("capture_threes_bridge_kills") val bridgeKills: Int = 0,
    @SerialName("capture_threes_damage_dealt") val damageDealt: Int = 0,
    @SerialName("capture_threes_losses") val losses: Int = 0,
    @SerialName("capture_threes_melee_hits") val meleeHits: Int = 0,
    @SerialName("capture_threes_melee_swings") val meleeSwings: Int = 0,
    @SerialName("capture_threes_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("capture_threes_captures") val captures: Int = 0,
    @SerialName("capture_threes_wins") val wins: Int = 0,
    @SerialName("best_winstreak_mode_capture_threes") val bestWinstreak: Int = 0,
    @SerialName("capture_threes_golden_apples_eaten") val goldenApplesEaten: Int = 0,
)

@Serializable
data class BridgeDoublesDuels(
    @SerialName("bridge_doubles_wins") val wins: Int = 0,
    @SerialName("bridge_doubles_deaths") val deaths: Int = 0,
    @SerialName("bridge_doubles_goals") val goals: Int = 0,
    @SerialName("bridge_doubles_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("bridge_doubles_kills") val kills: Int = 0,
    @SerialName("current_winstreak_mode_bridge_doubles") val currentWinstreak: Int = 0,
    @SerialName("best_winstreak_mode_bridge_doubles") val bestWinstreak: Int = 0,
    @SerialName("bridge_doubles_damage_dealt") val damageDealt: Int = 0,
    @SerialName("bridge_doubles_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("bridge_doubles_blocks_placed") val blocksPlaced: Int = 0,
    @SerialName("bridge_doubles_bow_shots") val bowShots: Int = 0,
    @SerialName("bridge_doubles_melee_swings") val meleeSwings: Int = 0,
    @SerialName("bridge_doubles_bow_hits") val bowHits: Int = 0,
    @SerialName("bridge_doubles_melee_hits") val meleeHits: Int = 0,
    @SerialName("duels_winstreak_best_bridge_doubles") val duelsWinstreakBest: Int = 0,
    @SerialName("bridge_doubles_losses") val losses: Int = 0,
    @SerialName("bridge_doubles_bridge_deaths") val bridgeDeaths: Int = 0,
    @SerialName("bridge_doubles_bridge_kills") val bridgeKills: Int = 0,
    @SerialName("bridge_doubles_golden_apples_eaten") val goldenApplesEaten: Int = 0,
)

@Serializable
data class BridgeDuels(
    @SerialName("bridge_duel_wins") val wins: Int = 0,
    @SerialName("bridge_duel_deaths") val deaths: Int = 0,
    @SerialName("bridge_duel_goals") val goals: Int = 0,
    @SerialName("bridge_duel_kills") val kills: Int = 0,
    @SerialName("bridge_duel_losses") val losses: Int = 0,
    @SerialName("bridge_duel_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("current_winstreak_mode_bridge_duel") val currentWinstreak: Int = 0,
    @SerialName("best_winstreak_mode_bridge_duel") val bestWinstreak: Int = 0,
    @SerialName("bridge_duel_damage_dealt") val damageDealt: Int = 0,
    @SerialName("bridge_duel_melee_hits") val meleeHits: Int = 0,
    @SerialName("bridge_duel_blocks_placed") val blocksPlaced: Int = 0,
    @SerialName("bridge_duel_melee_swings") val meleeSwings: Int = 0,
    @SerialName("bridge_duel_bow_shots") val bowShots: Int = 0,
    @SerialName("bridge_duel_bow_hits") val bowHits: Int = 0,
    @SerialName("duels_winstreak_best_bridge_duel") val duelsWinstreakBest: Int = 0,
    @SerialName("bridge_duel_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("bridge_duel_bridge_deaths") val bridgeDeaths: Int = 0,
    @SerialName("bridge_duel_bridge_kills") val bridgeKills: Int = 0,
    @SerialName("bridge_duel_golden_apples_eaten") val goldenApplesEaten: Int = 0,
)

@Serializable
data class BridgeFourThreeDuels(
    @SerialName("bridge_3v3v3v3_deaths") val deaths: Int = 0,
    @SerialName("bridge_3v3v3v3_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("bridge_3v3v3v3_wins") val wins: Int = 0,
    @SerialName("bridge_3v3v3v3_kills") val kills: Int = 0,
    @SerialName("bridge_3v3v3v3_goals") val goals: Int = 0,
    @SerialName("best_winstreak_mode_bridge_3v3v3v3") val bestWinstreak: Int = 0,
    @SerialName("current_winstreak_mode_bridge_3v3v3v3") val currentWinstreak: Int = 0,
    @SerialName("bridge_3v3v3v3_bow_hits") val bowHits: Int = 0,
    @SerialName("bridge_3v3v3v3_melee_hits") val meleeHits: Int = 0,
    @SerialName("bridge_3v3v3v3_blocks_placed") val blocksPlaced: Int = 0,
    @SerialName("bridge_3v3v3v3_melee_swings") val meleeSwings: Int = 0,
    @SerialName("bridge_3v3v3v3_bridge_deaths") val bridgeDeaths: Int = 0,
    @SerialName("bridge_3v3v3v3_bow_shots") val bowShots: Int = 0,
    @SerialName("bridge_3v3v3v3_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("bridge_3v3v3v3_bridge_kills") val bridgeKills: Int = 0,
    @SerialName("bridge_3v3v3v3_damage_dealt") val damageDealt: Int = 0,
    @SerialName("duels_winstreak_best_bridge_3v3v3v3") val duelsWinstreakBest: Int = 0,
    @SerialName("bridge_3v3v3v3_losses") val losses: Int = 0,
)

@Serializable
data class BridgeFourTwoDuels(
    @SerialName("best_winstreak_mode_bridge_2v2v2v2") val bestWinstreak: Int = 0,
    @SerialName("current_winstreak_mode_bridge_2v2v2v2") val currentWinstreak: Int = 0,
    @SerialName("bridge_2v2v2v2_goals") val goals: Int = 0,
    @SerialName("bridge_2v2v2v2_blocks_placed") val blocksPlaced: Int = 0,
    @SerialName("bridge_2v2v2v2_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("bridge_2v2v2v2_melee_swings") val meleeSwings: Int = 0,
    @SerialName("bridge_2v2v2v2_bow_hits") val bowHits: Int = 0,
    @SerialName("bridge_2v2v2v2_wins") val wins: Int = 0,
    @SerialName("bridge_2v2v2v2_damage_dealt") val damageDealt: Int = 0,
    @SerialName("bridge_2v2v2v2_bridge_kills") val bridgeKills: Int = 0,
    @SerialName("bridge_2v2v2v2_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("bridge_2v2v2v2_bow_shots") val bowShots: Int = 0,
    @SerialName("bridge_2v2v2v2_bridge_deaths") val bridgeDeaths: Int = 0,
    @SerialName("bridge_2v2v2v2_melee_hits") val meleeHits: Int = 0,
    @SerialName("bridge_2v2v2v2_kills") val kills: Int = 0,
    @SerialName("bridge_2v2v2v2_losses") val losses: Int = 0,
    @SerialName("bridge_2v2v2v2_deaths") val deaths: Int = 0,
    @SerialName("duels_winstreak_best_bridge_2v2v2v2") val duelsWinstreakBest: Int = 0,
)

@Serializable
data class Bridge4v4Duels(
    @SerialName("current_winstreak_mode_bridge_four") val currentWinstreak: Int = 0,
    @SerialName("best_winstreak_mode_bridge_four") val bestWinstreak: Int = 0,
    @SerialName("bridge_four_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("bridge_four_damage_dealt") val damageDealt: Int = 0,
    @SerialName("bridge_four_goals") val goals: Int = 0,
    @SerialName("bridge_four_wins") val wins: Int = 0,
    @SerialName("bridge_four_blocks_placed") val blocksPlaced: Int = 0,
    @SerialName("bridge_four_melee_swings") val meleeSwings: Int = 0,
    @SerialName("bridge_four_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("bridge_four_melee_hits") val meleeHits: Int = 0,
    @SerialName("duels_winstreak_best_bridge_four") val duelsWinstreakBest: Int = 0,
    @SerialName("bridge_four_bow_hits") val bowHits: Int = 0,
    @SerialName("bridge_four_bow_shots") val bowShots: Int = 0,
    @SerialName("bridge_four_losses") val losses: Int = 0,
    @SerialName("bridge_four_bridge_deaths") val bridgeDeaths: Int = 0,
    @SerialName("bridge_four_bridge_kills") val bridgeKills: Int = 0,
    @SerialName("bridge_four_deaths") val deaths: Int = 0,
    @SerialName("bridge_four_kills") val kills: Int = 0,
    @SerialName("bridge_four_golden_apples_eaten") val goldenApplesEaten: Int = 0,
)

@Serializable
data class BridgeTournamentDuels(
    @SerialName("bridge_tournament_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("bridge_tournament_losses") val losses: Int = 0,
    @SerialName("bridge_tournament_bow_shots") val bowShots: Int = 0,
    @SerialName("bridge_tournament_damage_dealt") val damageDealt: Int = 0,
    @SerialName("bridge_tournament_melee_hits") val meleeHits: Int = 0,
    @SerialName("bridge_tournament_bow_hits") val bowHits: Int = 0,
    @SerialName("bridge_tournament_melee_swings") val meleeSwings: Int = 0,
    @SerialName("bridge_tournament_blocks_placed") val blocksPlaced: Int = 0,
    @SerialName("bridge_tournament_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("bridge_tournament_kills") val kills: Int = 0,
    @SerialName("bridge_tournament_goals") val goals: Int = 0,
    @SerialName("bridge_tournament_deaths") val deaths: Int = 0,
    @SerialName("bridge_tournament_wins") val wins: Int = 0,
    @SerialName("bridge_tournament_bridge_kills") val bridgeKills: Int = 0,
    @SerialName("bridge_tournament_bridge_deaths") val bridgeDeaths: Int = 0,
)

@Serializable
data class ClassicDuels(
    @SerialName("classic_duel_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("classic_duel_melee_hits") val meleeHits: Int = 0,
    @SerialName("classic_duel_kills") val kills: Int = 0,
    @SerialName("classic_duel_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("classic_duel_damage_dealt") val damageDealt: Int = 0,
    @SerialName("classic_duel_bow_hits") val bowHits: Int = 0,
    @SerialName("classic_duel_bow_shots") val bowShots: Int = 0,
    @SerialName("classic_duel_melee_swings") val meleeSwings: Int = 0,
    @SerialName("classic_duel_wins") val wins: Int = 0,
    @SerialName("classic_duel_losses") val losses: Int = 0,
    @SerialName("classic_duel_deaths") val deaths: Int = 0,
    @SerialName("duels_winstreak_best_classic_duel") val duelsWinstreakBest: Int = 0,
    @SerialName("current_winstreak_mode_classic_duel") val currentWinstreak: Int = 0,
    @SerialName("best_winstreak_mode_classic_duel") val bestWinstreak: Int = 0,
    @SerialName("duels_winstreak_classic_duel") val duelsWinstreak: Int = 0,
)

@Serializable
data class ComboDuels(
    @SerialName("duels_winstreak_combo_duel") val duelsWinstreak: Int = 0,
    @SerialName("duels_winstreak_best_combo_duel") val duelsWinstreakBest: Int = 0,
    @SerialName("combo_duel_melee_hits") val meleeHits: Int = 0,
    @SerialName("combo_duel_wins") val wins: Int = 0,
    @SerialName("combo_duel_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("combo_duel_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("combo_duel_melee_swings") val meleeSwings: Int = 0,
    @SerialName("combo_duel_kills") val kills: Int = 0,
    @SerialName("combo_duel_deaths") val deaths: Int = 0,
    @SerialName("combo_duel_losses") val losses: Int = 0,
    @SerialName("current_winstreak_mode_combo_duel") val currentWinstreak: Int = 0,
    @SerialName("combo_duel_golden_apples_eaten") val goldenApplesEaten: Int = 0,
    @SerialName("best_winstreak_mode_combo_duel") val bestWinstreak: Int = 0,
    @SerialName("combo_duel_damage_dealt") val damageDealt: Int = 0,
    @SerialName("combo_duel_bow_hits") val bowHits: Int = 0,
)

@Serializable
data class MegaWallsDoublesDuels(
    @SerialName("mw_doubles_melee_hits") val meleeHits: Int = 0,
    @SerialName("mw_doubles_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("mw_doubles_damage_dealt") val damageDealt: Int = 0,
    @SerialName("mw_doubles_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("mw_doubles_bow_hits") val bowHits: Int = 0,
    @SerialName("mw_doubles_bow_shots") val bowShots: Int = 0,
    @SerialName("mw_doubles_melee_swings") val meleeSwings: Int = 0,
    @SerialName("mw_doubles_assassin_kit_wins") val assassinKitWins: Int = 0,
    @SerialName("mw_doubles_wins") val wins: Int = 0,
    @SerialName("mw_doubles_kit_wins") val kitWins: Int = 0,
    @SerialName("mw_doubles_kills") val kills: Int = 0,
    @SerialName("mw_doubles_deaths") val deaths: Int = 0,
    @SerialName("mw_doubles_losses") val losses: Int = 0,
    @SerialName("mw_doubles_blocks_placed") val blocksPlaced: Int = 0,
    @SerialName("current_winstreak_mode_mw_doubles") val currentWinstreak: Int = 0,
    @SerialName("best_winstreak_mode_mw_doubles") val bestWinstreak: Int = 0,
    @SerialName("mw_doubles_zombie_kit_wins") val zombieKitWins: Int = 0,
    @SerialName("mw_doubles_arcanist_kit_wins") val arcanistKitWins: Int = 0,
    @SerialName("mw_doubles_renegade_kit_wins") val renegadeKitWins: Int = 0,
    @SerialName("duels_winstreak_best_mw_doubles") val duelsWinstreakBest: Int = 0,
    @SerialName("mw_doubles_phoenix_kit_wins") val phoenixKitWins: Int = 0,
    @SerialName("mw_doubles_herobrine_kit_wins") val herobrineKitWins: Int = 0,
    @SerialName("mw_doubles_snowman_kit_wins") val snowmanKitWins: Int = 0,
)

@Serializable
data class MegaWallsDuels(
    @SerialName("mw_duels_class") val sClass: String = "",
    @SerialName("mw_duel_losses") val losses: Int = 0,
    @SerialName("mw_duel_melee_hits") val meleeHits: Int = 0,
    @SerialName("mw_duel_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("mw_duel_damage_dealt") val damageDealt: Int = 0,
    @SerialName("mw_duel_melee_swings") val meleeSwings: Int = 0,
    @SerialName("mw_duel_deaths") val deaths: Int = 0,
    @SerialName("mw_duel_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("mw_duel_dreadlord_kit_wins") val dreadlordKitWins: Int = 0,
    @SerialName("mw_duel_kit_wins") val kitWins: Int = 0,
    @SerialName("mw_duel_kills") val kills: Int = 0,
    @SerialName("mw_duel_wins") val wins: Int = 0,
    @SerialName("mw_duel_blocks_placed") val blocksPlaced: Int = 0,
    @SerialName("mw_duel_bow_shots") val bowShots: Int = 0,
    @SerialName("mw_duel_bow_hits") val bowHits: Int = 0,
    @SerialName("mw_duel_blaze_kit_wins") val blazeKitWins: Int = 0,
    @SerialName("duels_winstreak_best_mw_duel") val duelsWinstreakBest: Int = 0,
    @SerialName("mw_duel_pirate_kit_wins") val pirateKitWins: Int = 0,
    @SerialName("mw_duel_shark_kit_wins") val sharkKitWins: Int = 0,
    @SerialName("mw_duel_pigman_kit_wins") val pigmanKitWins: Int = 0,
    @SerialName("mw_duel_assassin_kit_wins") val assassinKitWins: Int = 0,
    @SerialName("mw_duel_renegade_kit_wins") val renegadeKitWins: Int = 0,
    @SerialName("mw_duel_zombie_kit_wins") val zombieKitWins: Int = 0,
    @SerialName("mw_duel_golem_kit_wins") val golemKitWins: Int = 0,
    @SerialName("mw_duel_herobrine_kit_wins") val herobrineKitWins: Int = 0,
    @SerialName("mw_duel_snowman_kit_wins") val snowmanKitWins: Int = 0,
    @SerialName("mw_duel_arcanist_kit_wins") val arcanistKitWins: Int = 0,
    @SerialName("mw_duel_shaman_kit_wins") val shamanKitWins: Int = 0,
    @SerialName("current_winstreak_mode_mw_duel") val currentWinstreak: Int = 0,
    @SerialName("best_winstreak_mode_mw_duel") val bestWinstreak: Int = 0,
    @SerialName("mw_duel_squid_kit_wins") val squidKitWins: Int = 0,
    @SerialName("mw_duel_phoenix_kit_wins") val phoenixKitWins: Int = 0,
    @SerialName("mw_duel_moleman_kit_wins") val molemanKitWins: Int = 0,
    @SerialName("mw_duel_skeleton_kit_wins") val skeletonKitWins: Int = 0,
    @SerialName("mw_duel_werewolf_kit_wins") val werewolfKitWins: Int = 0,
    @SerialName("mw_duel_cow_kit_wins") val cowKitWins: Int = 0,
    @SerialName("mw_duel_enderman_kit_wins") val endermanKitWins: Int = 0,
    @SerialName("duels_winstreak_mw_duel") val duelsWinstreak: Int = 0,
    @SerialName("mw_duel_hunter_kit_wins") val hunterKitWins: Int = 0,
    @SerialName("mw_duel_automaton_kit_wins") val automatonKitWins: Int = 0,
)

@Serializable
data class MegaWallsTeamsDuels(
    @SerialName("mw_four_kit_wins") val kitWins: Int = 0,
    @SerialName("mw_four_kills") val kills: Int = 0,
    @SerialName("mw_four_dreadlord_kit_wins") val dreadlordKitWins: Int = 0,
    @SerialName("mw_four_melee_hits") val meleeHits: Int = 0,
    @SerialName("mw_four_damage_dealt") val damageDealt: Int = 0,
    @SerialName("mw_four_bow_shots") val bowShots: Int = 0,
    @SerialName("mw_four_bow_hits") val bowHits: Int = 0,
    @SerialName("mw_four_wins") val wins: Int = 0,
    @SerialName("mw_four_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("mw_four_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("mw_four_melee_swings") val meleeSwings: Int = 0,
    @SerialName("duels_winstreak_best_mw_four") val duelsWinstreakBest: Int = 0,
)

@Serializable
data class NoDebuffDuels(
    @SerialName("potion_duel_deaths") val deaths: Int = 0,
    @SerialName("potion_duel_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("potion_duel_melee_hits") val meleeHits: Int = 0,
    @SerialName("potion_duel_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("potion_duel_heal_pots_used") val healPotsUsed: Int = 0,
    @SerialName("potion_duel_melee_swings") val meleeSwings: Int = 0,
    @SerialName("potion_duel_losses") val losses: Int = 0,
    @SerialName("potion_duel_damage_dealt") val damageDealt: Int = 0,
    @SerialName("current_winstreak_mode_potion_duel") val currentWinstreak: Int = 0,
    @SerialName("duels_winstreak_best_potion_duel") val duelsWinstreakBest: Int = 0,
    @SerialName("potion_duel_bow_hits") val bowHits: Int = 0,
    @SerialName("potion_duel_kills") val kills: Int = 0,
    @SerialName("potion_duel_wins") val wins: Int = 0,
    @SerialName("best_winstreak_mode_potion_duel") val bestWinstreak: Int = 0,
)

@Serializable
data class OPDoublesDuels(
    @SerialName("duels_winstreak_best_op_doubles") val duelsWinstreakBest: Int = 0,
    @SerialName("op_doubles_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("op_doubles_melee_hits") val meleeHits: Int = 0,
    @SerialName("op_doubles_wins") val wins: Int = 0,
    @SerialName("op_doubles_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("op_doubles_kills") val kills: Int = 0,
    @SerialName("op_doubles_damage_dealt") val damageDealt: Int = 0,
    @SerialName("op_doubles_melee_swings") val meleeSwings: Int = 0,
    @SerialName("op_doubles_deaths") val deaths: Int = 0,
    @SerialName("op_doubles_losses") val losses: Int = 0,
    @SerialName("op_doubles_bow_hits") val bowHits: Int = 0,
    @SerialName("op_doubles_bow_shots") val bowShots: Int = 0,
    @SerialName("current_winstreak_mode_op_doubles") val currentWinstreak: Int = 0,
    @SerialName("best_winstreak_mode_op_doubles") val bestWinstreak: Int = 0,
)

@Serializable
data class OPDuels(
    @SerialName("op_duel_damage_dealt") val damageDealt: Int = 0,
    @SerialName("op_duel_kills") val kills: Int = 0,
    @SerialName("op_duel_melee_swings") val meleeSwings: Int = 0,
    @SerialName("op_duel_melee_hits") val meleeHits: Int = 0,
    @SerialName("op_duel_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("op_duel_wins") val wins: Int = 0,
    @SerialName("op_duel_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("duels_winstreak_best_op_duel") val duelsWinstreakBest: Int = 0,
    @SerialName("op_duel_deaths") val deaths: Int = 0,
    @SerialName("op_duel_losses") val losses: Int = 0,
    @SerialName("current_winstreak_mode_op_duel") val currentWinstreak: Int = 0,
    @SerialName("best_winstreak_mode_op_duel") val bestWinstreak: Int = 0,
    @SerialName("op_duel_bow_shots") val bowShots: Int = 0,
    @SerialName("op_duel_bow_hits") val bowHits: Int = 0,
    @SerialName("duels_winstreak_op_duel") val duelsWinstreak: Int = 0,
)

@Serializable
data class ParkourDuels(
    @SerialName("parkour_eight_deaths") val deaths: Int = 0,
    @SerialName("parkour_eight_losses") val losses: Int = 0,
    @SerialName("parkour_eight_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("parkour_eight_wins") val wins: Int = 0,
    @SerialName("best_winstreak_mode_parkour_eight") val bestWinstreak: Int = 0,
)

@Serializable
data class SkywarsDoublesDuels(
    @SerialName("duels_winstreak_best_sw_doubles") val duelsWinstreakBest: Int = 0,
    @SerialName("sw_doubles_melee_swings") val meleeSwings: Int = 0,
    @SerialName("sw_doubles_kit_wins") val kitWins: Int = 0,
    @SerialName("sw_doubles_kills") val kills: Int = 0,
    @SerialName("sw_doubles_melee_hits") val meleeHits: Int = 0,
    @SerialName("sw_doubles_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("sw_doubles_wins") val wins: Int = 0,
    @SerialName("sw_doubles_damage_dealt") val damageDealt: Int = 0,
    @SerialName("sw_doubles_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("sw_doubles_hellhound_kit_wins") val hellhoundKitWins: Int = 0,
    @SerialName("sw_doubles_deaths") val deaths: Int = 0,
    @SerialName("sw_doubles_losses") val losses: Int = 0,
    @SerialName("sw_doubles_scout_kit_wins") val scoutKitWins: Int = 0,
    @SerialName("sw_doubles_bow_shots") val bowShots: Int = 0,
    @SerialName("sw_doubles_bow_hits") val bowHits: Int = 0,
    @SerialName("sw_doubles_blocks_placed") val blocksPlaced: Int = 0,
    @SerialName("best_winstreak_mode_sw_doubles") val bestWinstreak: Int = 0,
    @SerialName("current_winstreak_mode_sw_doubles") val currentWinstreak: Int = 0,
    @SerialName("sw_doubles_pyromancer_kit_wins") val pyromancerKitWins: Int = 0,
    @SerialName("sw_doubles_champion_kit_wins") val championKitWins: Int = 0,
    @SerialName("duels_winstreak_sw_doubles") val duelsWinstreak: Int = 0,
    @SerialName("sw_doubles_healer_kit_wins") val healerKitWins: Int = 0,
    @SerialName("sw_doubles_armorer_kit_wins") val armorerKitWins: Int = 0,
    @SerialName("sw_doubles_bowman_kit_wins") val bowmanKitWins: Int = 0,
    @SerialName("sw_doubles_enchanter_kit_wins") val enchanterKitWins: Int = 0,
    @SerialName("sw_doubles_skeletor_kit_wins") val skeletorKitWins: Int = 0,
    @SerialName("sw_doubles_grenade_kit_wins") val grenadeKitWins: Int = 0,
    @SerialName("sw_doubles_snowman_kit_wins") val snowmanKitWins: Int = 0,
    @SerialName("sw_doubles_sloth_kit_wins") val slothKitWins: Int = 0,
    @SerialName("sw_doubles_rookie_kit_wins") val rookieKitWins: Int = 0,
    @SerialName("sw_doubles_engineer_kit_wins") val engineerKitWins: Int = 0,
    @SerialName("sw_doubles_witch_kit_wins") val witchKitWins: Int = 0,
    @SerialName("sw_doubles_hound_kit_wins") val houndKitWins: Int = 0,
    @SerialName("sw_doubles_troll_kit_wins") val trollKitWins: Int = 0,
    @SerialName("sw_doubles_hunter_kit_wins") val hunterKitWins: Int = 0,
    @SerialName("sw_doubles_ecologist_kit_wins") val ecologistKitWins: Int = 0,
    @SerialName("sw_doubles_enderchest_kit_wins") val enderchestKitWins: Int = 0,
    @SerialName("sw_doubles_guardian_kit_wins") val guardianKitWins: Int = 0,
    @SerialName("sw_doubles_jester_kit_wins") val jesterKitWins: Int = 0,
    @SerialName("sw_doubles_frog_kit_wins") val frogKitWins: Int = 0,
    @SerialName("sw_doubles_speleologist_kit_wins") val speleologistKitWins: Int = 0,
    @SerialName("sw_doubles_fisherman_kit_wins") val fishermanKitWins: Int = 0,
    @SerialName("sw_doubles_cannoneer_kit_wins") val cannoneerKitWins: Int = 0,
    @SerialName("sw_doubles_farmer_kit_wins") val farmerKitWins: Int = 0,
    @SerialName("sw_doubles_magician_kit_wins") val magicianKitWins: Int = 0,
    @SerialName("sw_doubles_paladin_kit_wins") val paladinKitWins: Int = 0,
    @SerialName("sw_doubles_golem_kit_wins") val golemKitWins: Int = 0,
)

@Serializable
data class SkywarsDuels(
    @SerialName("sw_duels_kit") val sKit: String = "",
    @SerialName("duels_winstreak_best_sw_duel") val duelsWinstreakBest: Int = 0,
    @SerialName("sw_duel_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("sw_duel_melee_swings") val meleeSwings: Int = 0,
    @SerialName("sw_duel_wins") val wins: Int = 0,
    @SerialName("sw_duel_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("sw_duel_kills") val kills: Int = 0,
    @SerialName("sw_duel_damage_dealt") val damageDealt: Int = 0,
    @SerialName("sw_duel_melee_hits") val meleeHits: Int = 0,
    @SerialName("sw_duel_kit_wins") val kitWins: Int = 0,
    @SerialName("sw_duel_scout_kit_wins") val scoutKitWins: Int = 0,
    @SerialName("sw_duel_deaths") val deaths: Int = 0,
    @SerialName("sw_duel_losses") val losses: Int = 0,
    @SerialName("sw_duel_armorer_kit_wins") val armorerKitWins: Int = 0,
    @SerialName("sw_duel_bow_shots") val bowShots: Int = 0,
    @SerialName("sw_duel_hound_kit_wins") val houndKitWins: Int = 0,
    @SerialName("sw_duel_bow_hits") val bowHits: Int = 0,
    @SerialName("sw_duels_kit_new") val sKitNew: String = "",
    @SerialName("sw_duel_bowman_kit_wins") val bowmanKitWins: Int = 0,
    @SerialName("sw_duels_kit_new2") val sKitNew2: String = "",
    @SerialName("sw_duel_blocks_placed") val blocksPlaced: Int = 0,
    @SerialName("sw_duel_champion_kit_wins") val championKitWins: Int = 0,
    @SerialName("current_winstreak_mode_sw_duel") val currentWinstreak: Int = 0,
    @SerialName("best_winstreak_mode_sw_duel") val bestWinstreak: Int = 0,
    @SerialName("sw_duel_pyromancer_kit_wins") val pyromancerKitWins: Int = 0,
    @SerialName("sw_duels_kit_new3") val sKitNew3: String = "",
    @SerialName("sw_duel_athlete_kit_wins") val athleteKitWins: Int = 0,
    @SerialName("sw_duel_ecologist_kit_wins") val ecologistKitWins: Int = 0,
    @SerialName("duels_winstreak_sw_duel") val duelsWinstreak: Int = 0,
    @SerialName("sw_duel_snowman_kit_wins") val snowmanKitWins: Int = 0,
    @SerialName("sw_duel_magician_kit_wins") val magicianKitWins: Int = 0,
    @SerialName("sw_duel_hellhound_kit_wins") val hellhoundKitWins: Int = 0,
    @SerialName("sw_duel_fisherman_kit_wins") val fishermanKitWins: Int = 0,
    @SerialName("sw_duel_grenade_kit_wins") val grenadeKitWins: Int = 0,
    @SerialName("sw_duel_zookeeper_kit_wins") val zookeeperKitWins: Int = 0,
    @SerialName("sw_duel_paladin_kit_wins") val paladinKitWins: Int = 0,
)

@Serializable
data class SkywarsTeamsDuels(
    @SerialName("") val kills: Int = 0
)

@Serializable
data class SkywarsTournamentDuels(
    @SerialName("sw_tournament_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("sw_tournament_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("sw_tournament_melee_hits") val meleeHits: Int = 0,
    @SerialName("sw_tournament_damage_dealt") val damageDealt: Int = 0,
    @SerialName("sw_tournament_melee_swings") val meleeSwings: Int = 0,
    @SerialName("sw_tournament_kills") val kills: Int = 0,
    @SerialName("sw_tournament_deaths") val deaths: Int = 0,
    @SerialName("sw_tournament_losses") val losses: Int = 0,
    @SerialName("sw_tournament_blocks_placed") val blocksPlaced: Int = 0,
    @SerialName("sw_tournament_wins") val wins: Int = 0,
    @SerialName("sw_tournament_bow_hits") val bowHits: Int = 0,
    @SerialName("sw_tournament_bow_shots") val bowShots: Int = 0,
    @SerialName("sw_tournament_heal_pots_used") val healPotsUsed: Int = 0,
)

@Serializable
data class SumoDuels(
    @SerialName("sumo_duel_melee_swings") val meleeSwings: Int = 0,
    @SerialName("sumo_duel_wins") val wins: Int = 0,
    @SerialName("sumo_duel_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("sumo_duel_melee_hits") val meleeHits: Int = 0,
    @SerialName("sumo_duel_losses") val losses: Int = 0,
    @SerialName("sumo_duel_deaths") val deaths: Int = 0,
    @SerialName("sumo_duel_kills") val kills: Int = 0,
    @SerialName("best_winstreak_mode_sumo_duel") val bestWinstreak: Int = 0,
    @SerialName("current_winstreak_mode_sumo_duel") val currentWinstreak: Int = 0,
)

@Serializable
data class SumoTournamentDuels(
    @SerialName("sumo_tournament_melee_hits") val meleeHits: Int = 0,
    @SerialName("sumo_tournament_melee_swings") val meleeSwings: Int = 0,
    @SerialName("sumo_tournament_losses") val losses: Int = 0,
    @SerialName("sumo_tournament_kills") val kills: Int = 0,
    @SerialName("sumo_tournament_deaths") val deaths: Int = 0,
    @SerialName("sumo_tournament_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("sumo_tournament_wins") val wins: Int = 0,
)

@Serializable
data class UHCDeathmatchDuels(
    @SerialName("uhc_meetup_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("uhc_meetup_bow_shots") val bowShots: Int = 0,
    @SerialName("uhc_meetup_melee_hits") val meleeHits: Int = 0,
    @SerialName("uhc_meetup_bow_hits") val bowHits: Int = 0,
    @SerialName("uhc_meetup_damage_dealt") val damageDealt: Int = 0,
    @SerialName("uhc_meetup_blocks_placed") val blocksPlaced: Int = 0,
    @SerialName("uhc_meetup_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("uhc_meetup_melee_swings") val meleeSwings: Int = 0,
    @SerialName("current_winstreak_mode_uhc_meetup") val currentWinstreak: Int = 0,
    @SerialName("uhc_meetup_deaths") val deaths: Int = 0,
    @SerialName("uhc_meetup_kills") val kills: Int = 0,
    @SerialName("uhc_meetup_losses") val losses: Int = 0,
    @SerialName("best_winstreak_mode_uhc_meetup") val bestWinstreak: Int = 0,
    @SerialName("uhc_meetup_wins") val wins: Int = 0,
    @SerialName("duels_winstreak_best_uhc_meetup") val duelsWinstreakBest: Int = 0,
)

@Serializable
data class UHCDoublesDuels(
    @SerialName("uhc_doubles_losses") val losses: Int = 0,
    @SerialName("uhc_doubles_kills") val kills: Int = 0,
    @SerialName("uhc_doubles_bow_shots") val bowShots: Int = 0,
    @SerialName("uhc_doubles_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("uhc_doubles_melee_swings") val meleeSwings: Int = 0,
    @SerialName("uhc_doubles_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("uhc_doubles_melee_hits") val meleeHits: Int = 0,
    @SerialName("uhc_doubles_deaths") val deaths: Int = 0,
    @SerialName("uhc_doubles_damage_dealt") val damageDealt: Int = 0,
    @SerialName("uhc_doubles_bow_hits") val bowHits: Int = 0,
    @SerialName("duels_winstreak_best_uhc_doubles") val duelsWinstreakBest: Int = 0,
    @SerialName("uhc_doubles_wins") val wins: Int = 0,
    @SerialName("current_winstreak_mode_uhc_doubles") val currentWinstreak: Int = 0,
    @SerialName("best_winstreak_mode_uhc_doubles") val bestWinstreak: Int = 0,
    @SerialName("uhc_doubles_golden_apples_eaten") val goldenApplesEaten: Int = 0,
    @SerialName("uhc_doubles_blocks_placed") val blocksPlaced: Int = 0,
)

@Serializable
data class UHCDuels(
    @SerialName("uhc_duel_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("uhc_duel_damage_dealt") val damageDealt: Int = 0,
    @SerialName("uhc_duel_melee_swings") val meleeSwings: Int = 0,
    @SerialName("uhc_duel_melee_hits") val meleeHits: Int = 0,
    @SerialName("duels_winstreak_best_uhc_duel") val duelsWinstreakBest: Int = 0,
    @SerialName("uhc_duel_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("uhc_duel_bow_shots") val bowShots: Int = 0,
    @SerialName("uhc_duel_kills") val kills: Int = 0,
    @SerialName("uhc_duel_bow_hits") val bowHits: Int = 0,
    @SerialName("uhc_duel_wins") val wins: Int = 0,
    @SerialName("uhc_duel_losses") val losses: Int = 0,
    @SerialName("uhc_duel_deaths") val deaths: Int = 0,
    @SerialName("uhc_duel_golden_apples_eaten") val goldenApplesEaten: Int = 0,
    @SerialName("uhc_duel_blocks_placed") val blocksPlaced: Int = 0,
    @SerialName("current_winstreak_mode_uhc_duel") val currentWinstreak: Int = 0,
    @SerialName("best_winstreak_mode_uhc_duel") val bestWinstreak: Int = 0,
    @SerialName("duels_winstreak_uhc_duel") val duelsWinstreak: Int = 0,
)

@Serializable
data class UHCTeamsDuels(
    @SerialName("uhc_four_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("uhc_four_melee_swings") val meleeSwings: Int = 0,
    @SerialName("uhc_four_bow_hits") val bowHits: Int = 0,
    @SerialName("uhc_four_melee_hits") val meleeHits: Int = 0,
    @SerialName("uhc_four_wins") val wins: Int = 0,
    @SerialName("uhc_four_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("uhc_four_damage_dealt") val damageDealt: Int = 0,
    @SerialName("uhc_four_kills") val kills: Int = 0,
    @SerialName("uhc_four_bow_shots") val bowShots: Int = 0,
    @SerialName("duels_winstreak_best_uhc_four") val duelsWinstreakBest: Int = 0,
    @SerialName("uhc_four_golden_apples_eaten") val goldenApplesEaten: Int = 0,
    @SerialName("uhc_four_blocks_placed") val blocksPlaced: Int = 0,
    @SerialName("uhc_four_deaths") val deaths: Int = 0,
    @SerialName("uhc_four_losses") val losses: Int = 0,
    @SerialName("best_winstreak_mode_uhc_four") val bestWinstreak: Int = 0,
    @SerialName("current_winstreak_mode_uhc_four") val currentWinstreak: Int = 0,
    @SerialName("duels_winstreak_uhc_four") val duelsWinstreak: Int = 0,
)

@Serializable
data class UHCTournamentDuels(
    @SerialName("uhc_tournament_melee_hits") val meleeHits: Int = 0,
    @SerialName("uhc_tournament_health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("uhc_tournament_damage_dealt") val damageDealt: Int = 0,
    @SerialName("uhc_tournament_melee_swings") val meleeSwings: Int = 0,
    @SerialName("uhc_tournament_rounds_played") val roundsPlayed: Int = 0,
    @SerialName("uhc_tournament_bow_hits") val bowHits: Int = 0,
    @SerialName("uhc_tournament_bow_shots") val bowShots: Int = 0,
    @SerialName("uhc_tournament_kills") val kills: Int = 0,
    @SerialName("uhc_tournament_deaths") val deaths: Int = 0,
    @SerialName("uhc_tournament_losses") val losses: Int = 0,
    @SerialName("uhc_tournament_wins") val wins: Int = 0,
    @SerialName("uhc_tournament_golden_apples_eaten") val goldenApplesEaten: Int = 0,
    @SerialName("uhc_tournament_blocks_placed") val blocksPlaced: Int = 0,
)

@Serializable
data class OverallDuels(
    @SerialName("duels_recently_played") val duelsRecentlyPlayed: String = "",
    @SerialName("games_played_duels") val gamesPlayedDuels: Int = 0,
    @SerialName("show_lb_option") val showLbOption: String = "",
    @SerialName("melee_swings") val meleeSwings: Int = 0,
    @SerialName("melee_hits") val meleeHits: Int = 0,
    @SerialName("wins") val wins: Int = 0,
    @SerialName("rounds_played") val roundsPlayed: Int = 0,
    @SerialName("bow_shots") val bowShots: Int = 0,
    @SerialName("kills") val kills: Int = 0,
    @SerialName("bow_hits") val bowHits: Int = 0,
    @SerialName("health_regenerated") val healthRegenerated: Int = 0,
    @SerialName("damage_dealt") val damageDealt: Int = 0,
    @SerialName("selected_2") val selected2: String = "",
    @SerialName("selected_1") val selected1: String = "",
    @SerialName("current_winstreak") val currentWinstreak: Int = 0,
    @SerialName("best_overall_winstreak") val bestOverallWinstreak: Int = 0,
    @SerialName("losses") val losses: Int = 0,
    @SerialName("deaths") val deaths: Int = 0,
    @SerialName("chat_enabled") val chatEnabled: String = "",
    @SerialName("coins") val coins: Int = 0,
    @SerialName("active_cosmetictitle") val activeCosmeticTitle: String = "",
    @SerialName("duels_chests") val duelsChests: Int = 0,
    @SerialName("Duels_openedChests") val duelsOpenedchests: Int = 0,
    @SerialName("Duels_openedCommons") val duelsOpenedcommons: Int = 0,
    @SerialName("Duels_openedRares") val duelsOpenedrares: Int = 0,
    @SerialName("Duels_openedEpics") val duelsOpenedepics: Int = 0,
    @SerialName("active_emblem") val activeEmblem: String = "",
    @SerialName("Duels_openedLegendaries") val duelsOpenedLegendaries: Int = 0,
    @SerialName("active_victory_dance") val activeVictoryDance: String = "",
    @SerialName("active_auras") val activeAuras: String = "",
    @SerialName("active_kill_effect") val activeKillEffect: String = "",
    @SerialName("active_weaponpacks") val activeWeaponpacks: String = "",
    @SerialName("selected_1_new") val selected1New: String = "",
    @SerialName("selected_2_new") val selected2New: String = "",
    @SerialName("no_debuff_rookie_title_prestige") val noDebuffRookieTitlePrestige: Int = 0,
    @SerialName("op_rookie_title_prestige") val opRookieTitlePrestige: Int = 0,
    @SerialName("combo_rookie_title_prestige") val comboRookieTitlePrestige: Int = 0,
    @SerialName("skywars_diamond_title_prestige") val skywarsDiamondTitlePrestige: Int = 0,
    @SerialName("classic_rookie_title_prestige") val classicRookieTitlePrestige: Int = 0,
    @SerialName("tnt_games_rookie_title_prestige") val tntGamesRookieTitlePrestige: Int = 0,
    @SerialName("sumo_diamond_title_prestige") val sumoDiamondTitlePrestige: Int = 0,
    @SerialName("uhc_rookie_title_prestige") val uhcRookieTitlePrestige: Int = 0,
    @SerialName("tournament_rookie_title_prestige") val tournamentRookieTitlePrestige: Int = 0,
    @SerialName("bow_rookie_title_prestige") val bowRookieTitlePrestige: Int = 0,
    @SerialName("mega_walls_rookie_title_prestige") val megaWallsRookieTitlePrestige: Int = 0,
    @SerialName("all_modes_master_title_prestige") val allModesMasterTitlePrestige: Int = 0,
    @SerialName("blitz_diamond_title_prestige") val blitzDiamondTitlePrestige: Int = 0,
    @SerialName("blocks_placed") val blocksPlaced: Int = 0,
    @SerialName("progress_mode") val progressMode: String = "",
    @SerialName("status_field") val statusField: String = "",
    @SerialName("blitz_master_title_prestige") val blitzMasterTitlePrestige: Int = 0,
    @SerialName("heal_pots_used") val healPotsUsed: Int = 0,
    @SerialName("golden_apples_eaten") val goldenApplesEaten: Int = 0,
    @SerialName("goals") val goals: Int = 0,
    @SerialName("bridge_rookie_title_prestige") val bridgeRookieTitlePrestige: Int = 0,
    @SerialName("leaderboardPage_win_streak") val leaderboardpageWinStreak: Int = 0,
    @SerialName("leaderboardPage_wins") val leaderboardpageWins: Int = 0,
    @SerialName("bridge_iron_title_prestige") val bridgeIronTitlePrestige: Int = 0,
    @SerialName("active_goal") val activeGoal: String = "",
    @SerialName("skywars_master_title_prestige") val skywarsMasterTitlePrestige: Int = 0,
    @SerialName("leaderboardPage_goals") val leaderboardpageGoals: Int = 0,
    @SerialName("equipped_custom_titles") val equippedCustomTitles: String = "",
    @SerialName("classic_iron_title_prestige") val classicIronTitlePrestige: Int = 0,
    @SerialName("bridge_gold_title_prestige") val bridgeGoldTitlePrestige: Int = 0,
    @SerialName("challenges_enabled") val challengesEnabled: Boolean = true,
    @SerialName("all_modes_legend_title_prestige") val allModesLegendTitlePrestige: Int = 0,
    @SerialName("classic_gold_title_prestige") val classicGoldTitlePrestige: Int = 0,
    @SerialName("season_1_reward_fixes") val season1RewardFixes: Boolean = true,
    @SerialName("duels_recently_played2") val duelsRecentlyPlayed2: String = "",
    @SerialName("active_killmessages") val activeKillmessages: String = "",
    @SerialName("classic_diamond_title_prestige") val classicDiamondTitlePrestige: Int = 0,
    @SerialName("blitz_legend_title_prestige") val blitzLegendTitlePrestige: Int = 0,
    @SerialName("blitz_rookie_title_prestige") val blitzRookieTitlePrestige: Int = 0,
    @SerialName("sumo_master_title_prestige") val sumoMasterTitlePrestige: Int = 0,
    @SerialName("classic_master_title_prestige") val classicMasterTitlePrestige: Int = 0,
    @SerialName("classic_legend_title_prestige") val classicLegendTitlePrestige: Int = 0,
    @SerialName("duels_showqueuebook") val duelsShowqueuebook: Boolean = true,
    @SerialName("active_projectile_trail") val activeProjectileTrail: String = "",
    @SerialName("blitz_iron_title_prestige") val blitzIronTitlePrestige: Int = 0,
    @SerialName("all_modes_diamond_title_prestige") val allModesDiamondTitlePrestige: Int = 0,
    @SerialName("uhc_iron_title_prestige") val uhcIronTitlePrestige: Int = 0,
    @SerialName("sumo_legend_title_prestige") val sumoLegendTitlePrestige: Int = 0,
    @SerialName("active_cage") val activeCage: String = "",
    @SerialName("favoriteGlyph") val favoriteglyph: String = "",
    @SerialName("active_hat") val activeHat: String = "",
    @SerialName("bridge_diamond_title_prestige") val bridgeDiamondTitlePrestige: Int = 0,
    @SerialName("bridge_master_title_prestige") val bridgeMasterTitlePrestige: Int = 0,
    @SerialName("pingPreference") val pingPreference: Int = 0,
    @SerialName("sumo_rookie_title_prestige") val sumoRookieTitlePrestige: Int = 0,
    @SerialName("skywars_rookie_title_prestige") val skywarsRookieTitlePrestige: Int = 0,
    @SerialName("skywars_iron_title_prestige") val skywarsIronTitlePrestige: Int = 0,
    @SerialName("uhc_gold_title_prestige") val uhcGoldTitlePrestige: Int = 0,
    @SerialName("uhc_master_title_prestige") val uhcMasterTitlePrestige: Int = 0,
    @SerialName("skywars_gold_title_prestige") val skywarsGoldTitlePrestige: Int = 0,
    @SerialName("blitz_gold_title_prestige") val blitzGoldTitlePrestige: Int = 0,
    @SerialName("uhc_diamond_title_prestige") val uhcDiamondTitlePrestige: Int = 0,
    @SerialName("chat_option_kill_feed") val chatOptionKillFeed: String = "",
    @SerialName("special_challenger") val specialChallenger: Boolean = true,
    @SerialName("op_iron_title_prestige") val opIronTitlePrestige: Int = 0,
    @SerialName("skywars_legend_title_prestige") val skywarsLegendTitlePrestige: Int = 0,
    @SerialName("all_modes_iron_title_prestige") val allModesIronTitlePrestige: Int = 0,
    @SerialName("all_modes_gold_title_prestige") val allModesGoldTitlePrestige: Int = 0,
    @SerialName("all_modes_rookie_title_prestige") val allModesRookieTitlePrestige: Int = 0,
    @SerialName("tnt_games_iron_title_prestige") val tntGamesIronTitlePrestige: Int = 0,
    @SerialName("all_modes_grandmaster_title_prestige") val allModesGrandmasterTitlePrestige: Int = 0,
    @SerialName("uhc_legend_title_prestige") val uhcLegendTitlePrestige: Int = 0,
    @SerialName("classic_grandmaster_title_prestige") val classicGrandmasterTitlePrestige: Int = 0,
    @SerialName("show_map_detail") val showMapDetail: String = "",
    @SerialName("boxing_rookie_title_prestige") val boxingRookieTitlePrestige: Int = 0,
    @SerialName("parkour_rookie_title_prestige") val parkourRookieTitlePrestige: Int = 0,
    @SerialName("old_winstreak") val oldWinstreak: Int = 0,
    @SerialName("equipped_prefix_color") val equippedPrefixColor: String = "",
    @SerialName("equipped_prefix_icon") val equippedPrefixIcon: String = "",
    @SerialName("collected_reward_season_4") val collectedRewardSeason4: Boolean = true,
    @SerialName("toggle_proj_trail") val toggleProjTrail: String = "",
    @SerialName("collected_reward_season_5") val collectedRewardSeason5: Boolean = true,
    @SerialName("shop_sort") val shopSort: String = "",
    @SerialName("shop_sort_enable_owned_first") val shopSortEnableOwnedFirst: Boolean = true,
)